use_frameworks!

platform :ios, '10.0'

target 'ZXNavigationBarKit_Example' do
  pod 'ZXNavigationBarKit', :path => '../'

  target 'ZXNavigationBarKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
